source 'http://rubygems.org'

gem 'capybara', '~> 3.32', '>= 3.32.2'
gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver', '~> 4.0.0.alpha5'
gem 'ffi'
gem 'site_prism'
gem 'syntax'
gem 'byebug'
gem 'faker'